# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 964469d26b4b1f59d3c4281c091daa801d54a22f2cc437cd8dca253085ad4a41bd79aa0d935b83b8066dc1b074e394ba6691b5c47c040fb996af8ec6e80fbeaf

test:
  secret_key_base: 69a846bcefcc112d5045975d32511a0cc107b34289ec0b12c837fa1f40a793dac77f33d1add09193513a5ae0db51e45e15da58f3d0efff80ee5c8c283673a29b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
